name: gestion_de_vente
description: Tata Camm Solaire (avec verrou PIN)
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.11
  sqflite: ^2.2.8
  provider: ^6.0.5
  intl: ^0.18.0
  pdf: ^3.8.1
  printing: ^5.10.0
  csv: ^5.0.0
  permission_handler: ^10.4.0
  flutter_secure_storage: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
