name: gestion_de_vente_pro
description: Tata Camm Solaire (avec verrou PIN)
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  path_provider: ^2.1.2
  sqflite: ^2.3.2
  provider: ^6.1.2
  intl: ^0.19.0
  pdf: ^3.10.8
  printing: ^5.12.0
  csv: ^5.1.1
  permission_handler: ^11.3.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
